### ISSUE TITLE
Use annotations to modify the ingress-controller config

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#3844]
### Description:

I noticed we have been using a customized version of the nginx for Kind ingress-controller in which explicitly modified the buffer size.

I wonder whether we should be passing this config using annotations instead of maintaining the whole set of nginx manifests in our repo.

We should be able to replace [this file](https://github.com/kubeapps/kubeapps/blob/master/docs/user/manifests/ingress-nginx-kind-with-large-proxy-buffers.yaml) with:

```yaml
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4"
```

If so, we should add this fragment in the readme or FAQ to help other people solve their ingress issues.
