### ISSUE TITLE
possible backward incompatible change between 8.0.15 and 8.0.16

### ISSUE THREAD

**Issue by dlaloue-vmware** [vmware-tanzu/kubeapps#4691]
the change to the chart's values.yaml between 8.0.15 and 8.0.16 is a possible backward incompatible change.

the values file changed from something like:
```
postgresql:
  enabled: true
  auth:
    password: ""
```

to 
```
postgresql:
  enabled: true
  auth:
    postgresPassword: ""
```

as a user, i created a values.yaml file which provided a password using "postgres.auth.password" and installed kubeapps at a version prior to 8.0.16
i then re-installed kubeapps at the latest 8.0.17 and kubeapps stopped working due to issue #4689 as the password were not matching anymore.
