### ISSUE TITLE
SIGSEGV: segmentation violation code=0x1  reported by kubeapps-internal-kubeappsapis when we try to see applic

### ISSUE THREAD

**Issue by cmoulliard** [vmware-tanzu/kubeapps#4901]
**Describe the bug**
A `SIGSEGV: segmentation violation code=0x1`error is reported within the log of the  `kubeapps-internal-kubeappsapis` pod when we try to see all the applications deployed using the Kubeapps UI: `http://kubeapps.10.0.77.176.nip.io/#/c/default/ns/default/apps?allns=yes`

Error stack trace
```
I0610 05:21:15.913930       1 server_ctrl_packages.go:273] +kapp-controller GetInstalledPackageSummaries (cluster="default", namespace="")
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x150 pc=0x7f5812812aab]

goroutine 34819 [running]:
plugin/unnamed-bdb907f9873b31bfe7b66078f6536d2f1ed7c7c8.(*Server).buildInstalledPackageSummary(0x7f5812cb1be0, 0xc0009d30e0, 0x0, 0x20, {0xc0006123e0, 0x7})
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/src/github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapte
rs.go:146 +0xab
plugin/unnamed-bdb907f9873b31bfe7b66078f6536d2f1ed7c7c8.(*Server).GetInstalledPackageSummaries(0xc0008a8e40, {0x1e2b8a0, 0xc0013d4a20}, 0xc0006ea300)
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/src/github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packag
es.go:418 +0xdbd
github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/core/packages/v1alpha1.packagesServer.GetInstalledPackageSummaries({{}, {0xc0009a4a50, 0xc000446a68, 0xa3c1c5}}, {0
x1e2b8a0, 0xc0013d4a20}, 0xc0006ea300)
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/src/github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/core/packages/v1alpha1/packages.go:178 +0x369
github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/gen/core/packages/v1alpha1._PackagesService_GetInstalledPackageSummaries_Handler.func1({0x1e2b8a0, 0xc0013d4a20}, {
0x1aff060, 0xc0006ea300})
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/src/github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages_grpc.pb.go:246 +0x78
github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/server.LogRequest({0x1e2b8a0, 0xc0013d4a20}, {0x1aff060, 0xc0006ea300}, 0xc0000a2d60, 0xc000892270)
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/src/github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/server/server.go:53 +0x9a
github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/gen/core/packages/v1alpha1._PackagesService_GetInstalledPackageSummaries_Handler({0x1b3abe0, 0xc0004ee588}, {0x1e2b
8a0, 0xc0013d4a20}, 0xc00035a660, 0x1cd07f0)
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/src/github.com/vmware-tanzu/kubeapps/cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages_grpc.pb.go:248 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005aa700, {0x1e55068, 0xc00058eb60}, 0xc0002f8ea0, 0xc0009a4e10, 0x2903e28, 0x0)
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0005aa700, {0x1e55068, 0xc00058eb60}, 0xc0002f8ea0, 0x0)
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /bitnami/blacksmith-sandox/kubeapps-apis-2.4.5/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x294
```

**To Reproduce**

```
helm repo add bitnami https://charts.bitnami.com/bitnami
cat <<EOF > $HOME/tanzu/kubeapps-values.yml
dashboard:
  image:
    repository: bitnami/kubeapps-dashboard
kubeops:
  enabled: true
  image:
    repository: bitnami/kubeapps-kubeops
kubeappsapis:
  image:
    repository: bitnami/kubeapps-apis
  enabledPlugins:
    - resources
    - kapp-controller-packages
    - helm-packages
packaging:
  helm:
    enabled: true
  carvel:
    enabled: true
featureFlags:
  operators: false
EOF

kubectl create ns kubeapps
helm install kubeapps -n kubeapps bitnami/kubeapps -f $HOME/tanzu/kubeapps-values.yml
cat <<EOF | kubectl apply -f - 
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeapps-grpc
  namespace: kubeapps
spec:
  virtualhost:
    fqdn: kubeapps.$VM_IP.nip.io
  routes:
    - conditions:
      - prefix: /apis/
      pathRewritePolicy:
        replacePrefix:
        - replacement: /
      services:
      - name: kubeapps-internal-kubeappsapis
        port: 8080
        protocol: h2c
    - services:
      - name: kubeapps
        port: 80
EOF
kubectl create --namespace default serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
```

**Screenshots**
![Screenshot 2022-06-10 at 16 30 50](https://user-images.githubusercontent.com/463790/173088040-1f7de70f-3bff-4d59-b8c6-453df3614b5a.png)

**Desktop (please complete the following information):**
- Version: image: docker.io/bitnami/kubeapps-apis:2.4.5-debian-11-r0
- Kubernetes version: 1.23.6
- Package version: Helm v3.9.0
