### ISSUE TITLE
Add docs about how to create an AppRepo with proxy

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5005]
We've had an internal question about Kubeapps behind a proxy.

The `no_proxy` thing is important, otherwise, it won't work. 

We should re-check if our docs say so.

```
spec:
      containers:
      - env:
        - name: https_proxy
          value: http://192.168.10.10:8080/
        - name: http_proxy
          value: http://192.168.10.10:8080/
        - name: no_proxy
          value: 10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,localhost,127.0.0.1.svc,.svc.cluster.local
```
