### ISSUE TITLE
Support building docker images for ARM architectures

### ISSUE THREAD

**Issue by beni0888** [vmware-tanzu/kubeapps#5208]
**Summary**
Add/improve the support for developing the project using a computer with ARM architecture.

**Background and rationale**
Currently, the docker images build scripts don't specify the platform for the images, and they are built for `linux/amd64` (although I guess this could depend on the version of docker in use), so they cannot be run on computers with ARM processors.

**Description**
It should be possible to build the images for different architectures, including at least `linux/amd64` and `linux/arm64`.

**Acceptance criteria**
- Docker images can be built locally for a target platform by providing a parameter to the corresponding Make target.

**Additional context**
N/A

**Comment by antgamdia** [comment]
Somehow related to https://github.com/vmware-tanzu/kubeapps/issues/929, but note that this is just focused on customizing the makefile, not actually building our images multi-arch (yet).

**Comment by Trackhe** [comment]
Please add an node affinity like 
```
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
```

for the repo sync jobs because i only find they way to do it by hand. but it gets overwritten from kubeapps. add this until you support arm please. And i find that support 2023/Q3 is late compared to many other companys and projects.
