### ISSUE TITLE
Allow to override Helm values from Kubeapps

### ISSUE THREAD

**Issue by dud225** [vmware-tanzu/kubeapps#5459]
**Summary**
Some settings are server-specific so it may make sense to be able to set them for the whole platform rather than on a per-chart basis.

**Background and rationale**
We have a chart that sets up an ingress and a TLS certificate and we have multiple Kubeapps server each with its own FQDN. As a result, when an user creates a new Helm deployment he also must make sure the ingress FQDN set from the Helm values is correct.

Here is the part of the chart that creates this ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:     
  name: my_ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:      
        - {{ quote .Values.ingress.host }}
      secretName: {{ quote .Values.ingress.host }}
  {{- end }}
  rules:    
    - host: {{ quote .Values.ingress.host }}
     [...]
```

The problem with this implementation is that the user often forget to put the correct value to `.Values.ingress.host`, not to mention when he's not even aware of it.

**Description**
It would be nice to be able to set such value globally from Kubeapps as those kind of settings pertain to server-wide configuration.

**Additional context**
There is a similar request for schema: https://github.com/vmware-tanzu/kubeapps/issues/3535.
