### ISSUE TITLE
Unable to use any oidc provider in oauth-proxy (k3s/any ingress type)

### ISSUE THREAD

**Issue by loic-roux-404** [vmware-tanzu/kubeapps#5754]
**Describe the bug**

Redirected to login page after a successful oidc login with dex.

**To Reproduce**

- all code : https://github.com/esgi-lyon/paas-tutorial
- kubeapps_k8s_ingress_class: traefik (tried nginx)

The ansible role https://github.com/PyratLabs/ansible-role-k3s is configured like that

also tried using native oidc features
```
      k3s_server:
        kube-apiserver-arg=oidc-issuer-url: "https://{{ kubeapps_dex_hostname }}"
        kube-apiserver-arg=oidc-client-id: "{{ kubeapps_dex_client_id }}"
        kube-apiserver-arg=oidc-username-claim: email
        kube-apiserver-arg=oidc-groups-claim: groups
        kube-apiserver-arg=authorization-mode: Node,RBAC
```

kubeapps helm chart values
```yaml
ingress:
  tls: true
  enabled: true
  hostname: "{{ kubeapps_hostname }}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-acme-issuer
    kubernetes.io/ingress.class: "{{ kubeapps_k8s_ingress_class }}"
    traefik.frontend.passHostHeader: "true"
    traefik.backend.loadbalancer.sticky: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"

authProxy:
    enabled: true
    provider: oidc
    clientID: "{{ kubeapps_dex_client_id }}"
    clientSecret: "{{ kubeapps_dex_client_secret }}"
    # default to result of echo "not-good-secret" | base64
    cookieSecret: 'bm90LWdvb2Qtc2VjcmV0Cg=='
    extraFlags:
      - --cookie-refresh=2m
      - --oidc-issuer-url=https://{{ kubeapps_dex_hostname }}
      #- --redirect-url=https://{{ kubeapps_hostname }}/oauth2/callback
      - --set-authorization-header=true

    extraVolumeMounts:
    - name: pebble-ca-share
      mountPath: /etc/ssl/certs/pebble-ca.crt
      subPath: ca.crt

pinnipedProxy:
    enabled: true
    defaultPinnipedNamespace: default
    tls:
        # existingSecret: pinniped-proxy-tls
        caCertificate: pebble-ca-share
    extraVolumeMounts:
      - name: pebble-ca-share
        mountPath: /etc/ssl/certs/pebble-ca.crt
        subPath: ca.crt

frontend:
  proxypassAccessTokenAsBearer: true
  extraVolumes:
  - name: pebble-ca-share
    configMap:
       name: pebble-ca-share

clusters:
- name: default
  pinnipedConfig:
    enabled: true
  
```

dex helm chart (not really necessary i think, `github` provider configured under oauthProxy kubeapps helm chart produce same behaviour (redirect on login page after successful login).

```yaml
    service:
      ports:
        http:
          nodePort: 5556
    ingress:

      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-acme-issuer
        kubernetes.io/ingress.class: "{{ kubeapps_k8s_ingress_class }}"
        traefik.frontend.passHostHeader: "true"
        traefik.backend.loadbalancer.sticky: "true"
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: {{ kubeapps_dex_hostname }}
        paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
        - secretName: {{ kubeapps_dex_hostname }}-tls
          hosts:
            - {{ kubeapps_dex_hostname }}
    config:
      issuer: "https://{{ kubeapps_dex_hostname }}"
      web:
        http: 127.0.0.1:5556
      storage:
        type: kubernetes
        config:
          inCluster: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: '{{ kubeapps_dex_github_client_id }}'
          clientSecret: '{{ kubeapps_dex_github_client_secret }}'
          redirectURI: "https://{{ kubeapps_dex_hostname }}/callback"
          orgs:
          - name: '{{ kubeapps_dex_github_client_org }}'
            teams: 
            - '{{ kubeapps_dex_github_client_team }}'
      oauth2:
        skipApprovalScreen: true
      staticClients:
      - id: "{{ kubeapps_dex_client_id }}"
        redirectURIs:
        - 'https://{{ kubeapps_hostname }}/oauth2/callback'
        name: 'Kubeapps'
        secret: "{{ kubeapps_dex_client_secret }}"
      - id: default
        redirectURIs:
        - https://127.0.0.1/callback
        name: 'Default'
        secret:  "{{ kubeapps_dex_client_secret }}"
        trustedPeers:
        - "{{ kubeapps_dex_client_id }}"
      enablePasswordDB: true
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeapps-cluster-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: Group
    name: "{{ kubeapps_dex_github_client_org }}:{{ kubeapps_dex_github_client_team }}"
    namespace: default
```

1. Go to 'https://kubeapps.k3s.local/'
2. Click on 'Login OIDC provider'
3. Give github information
4. Redirect to login page without showing pods inside any namespace of default cluster

**Expected behavior**
Login redirect to kubeapps

If someone know if an issue has already produced this behaviour, it will be very nice for me as i'm stuck with this from about 1 month.

I've seen some things concerning the header not given to upstream in oauth proxy 

This also not resolving: 
```yaml
    frontend:
      proxypassAccessTokenAsBearer: true
```

This look promising : https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#alphaoptions

**Screenshots**

**Desktop (please complete the following information):**

- Version[ [2.6.1

- 2.6.1 with latest https://artifacthub.io/packages/helm/bitnami/kubeapps
- Kubernetes version `v1.21.14+k3s1`
- Package version helm k3s cattle (helm 3)

**Additional context**

Oauth proxy log

First login

```
2.0.7:42830 - e638117a-bb66-4b78-95d2-dde59934d6b8 - loic.roux.404@gmail.com [2022/11/30 09:29:37] [AuthSuccess] Authenticated via OAuth2: Session{email:loic.roux.404@gmail.com user: PreferredUsername: token:true id_token:true created:2022-11-30 09:29:37.407614564 +0000 UTC m=+1565.659270773 expires:2022-12-01 09:29:36.404851193 +0000 UTC m=+87964.656507194 groups:[esgi-lyon:ops-team]}
10.42.0.7:42830 - e638117a-bb66-4b78-95d2-dde59934d6b8 - - [2022/11/30 09:29:37] kubeapps.k3s.local GET - "/oauth2/callback?code=eqsfqqocdtw3aw7ea5wws22wa&state=FbDlUpAd7F0jPQEPpx83MEv7bZNuoC-ZBWePx3gZbPM%3A%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0" 302 24 0.015
10.42.0.7:42830 - c6d71500-4ec0-4884-9a97-76d4c878f79c - loic.roux.404@gmail.com [2022/11/30 09:29:37] kubeapps.k3s.local POST / "/apis/kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0" 200 0 0.015
10.42.0.7:42830 - 429fb84d-24d7-4dae-b06d-9c22ebe8a9bd - loic.roux.404@gmail.com [2022/11/30 09:29:38] kubeapps.k3s.local GET / "/clr-ui-dark.min.css.map" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0" 304 0 0.023
```

```
10.42.0.7:37366 - 493bf1ed-0059-4112-a271-53316fd17ca0 - - [2022/11/30 09:14:19] kubeapps.k3s.local GET - "/oauth2/start" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" 302 277 0.001
10.42.0.7:37366 - 45be18f5-326b-46b3-9f02-65f08b09eb9e - loic.roux.404@gmail.com [2022/11/30 09:14:32] kubeapps.k3s.local POST / "/apis/kubeappsapis.core.plugins.v1alpha1.PluginsService/GetConfiguredPlugins" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" 200 76 0.005
```

Corresponding call to api server

```
I1130 09:14:32.277465       1 namespaces.go:27] "+resources CheckNamespaceExists" cluster="default" namespace="default"
I1130 09:14:32.284543       1 server.go:62] Internal 7.152157ms /kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists
```

Pinniped concierg looks broken, probably because it's a k3s-controller that we need
```json
{"level":"error","timestamp":"2022-11-30T12:25:14.491291Z","caller":"go.pinniped.dev/internal/controllerlib/controller.go:219$controllerlib.(*controller).handleKey","message":"kube-cert-agent-controller: { } failed with: could not find a healthy kube-controller-manager pod (0 candidates)\n"}
{"level":"info","timestamp":"2022-11-30T12:25:14.554611Z","logger":"jwtcachefiller-controller","caller":"go.pinniped.dev/internal/controller/authenticator/jwtcachefiller/jwtcachefiller.go:119$jwtcachefiller.(*controller).Sync","message":"actual jwt authenticator and desired jwt authenticator are the same","jwtAuthenticator":{"name":"jwt-authenticator"},"issuer":"https://dex.k3s.local"}
```

Other strange thing is i have no log in pinniped-proxy container

![ezgif com-gif-maker](https://user-images.githubusercontent.com/47380500/204759963-338ddac3-8584-43e3-94fd-96a615800ec0.gif)

**Comment by loic-roux-404** [comment]
Grpc call log after using other options for authproxy and new annotations for ingress

```yaml
      extraFlags:
        - --oidc-issuer-url=https://{{ kubeapps_dex_hostname }}
        - --set-authorization-header=true
        - --set-xauthrequest=true
        - --pass-access-token=true 
        - --skip-auth-preflight
```

ingress

```yaml
    ingress:
      tls: true
      enabled: true
      hostname: "{{ kubeapps_hostname }}"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-acme-issuer
        kubernetes.io/ingress.class: "{{ kubeapps_k8s_ingress_class }}"
        traefik.frontend.passHostHeader: "true"
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/auth-trust-headers: "true"
        ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, Authorization, Set-Cookie"

```

```
grpc-message: unable to get the Namespace 'default' due to 'an error on the server ("Failed to exchange credentials") has prevented the request from succeeding (get namespaces default)'
```
