### ISSUE TITLE
Unauthorized response in GetPackageRepositorySummaries

### ISSUE THREAD

**Issue by mecampbellsoup** [vmware-tanzu/kubeapps#5999]
```
Invalid GetPackageRepositorySummaries response from the plugin helm.packages: rpc error: code = Unauthenticated desc = Authorization required to get the AppRepository 'all' due to 'Unauthorized'
```

We're trying to upgrade to kubeapps 2.6.3 (latest release) and I've encountered a strange bug when trying to load the `Catalog`.

Seemingly due to an Unauthorized GRPC response, the dashboard redirects back to `/` and I end up right where I started (i.e. main dashboard page viewing applications).

1. Load kubeapps
2. Click `Catalog`
3. Redirected back to dashboard

![image](https://user-images.githubusercontent.com/2043821/219078380-4b01772d-5489-4bc4-91bc-ed3a109d83c2.png)
![image](https://user-images.githubusercontent.com/2043821/219078427-dbd75685-01f8-4707-9082-f8e09d0d7dac.png)
![image](https://user-images.githubusercontent.com/2043821/219078489-53f8a556-771e-4100-994f-4dc72187d671.png)

Is there some new configuration now that we need to do to permit our users to view package repositories?

We have 2 `AppRepository` configured in this cluster (BTW what is the difference to the "PackageRepository" concept?):

```
(⎈ default:kubeapps)mcampbell-1 :: coreweave/k8s-services/dev ‹master*› » k neat get apprepository
apiVersion: v1
items:
- apiVersion: kubeapps.com/v1alpha1
  kind: AppRepository
  metadata:
    annotations:
      meta.helm.sh/release-name: kubeapps
      meta.helm.sh/release-namespace: kubeapps
    labels:
      app.kubernetes.io/instance: kubeapps
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubeapps
      helm.sh/chart: kubeapps-12.2.1-dev0
    name: ant-repo
    namespace: kubeapps
  spec:
    syncJobPodTemplate:
      spec:
        securityContext:
          runAsUser: 1001
    type: helm
    url: http://charts.tenant-rizzo.ord1.ingress.coreweave.cloud/
- apiVersion: kubeapps.com/v1alpha1
  kind: AppRepository
  metadata:
    annotations:
      meta.helm.sh/release-name: kubeapps
      meta.helm.sh/release-namespace: kubeapps
    labels:
      app.kubernetes.io/instance: kubeapps
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubeapps
      helm.sh/chart: kubeapps-12.2.1-dev0
    name: coreweave
    namespace: kubeapps
  spec:
    syncJobPodTemplate:
      spec:
        securityContext:
          runAsUser: 1001
    type: helm
    url: http://helm.corp.ingress.ord1.coreweave.com/
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by mecampbellsoup** [comment]
I noticed that the request is using context of `cluster="" namespace=""`.

I hard-coded those values to `cluster="default" namespace="kubeapps"` and these requests started working as expected.

```git
diff --git a/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go b/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
index 5782e3907..004927670 100644
--- a/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
+++ b/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
@@ -563,12 +563,12 @@ func (s *Server) repoSummaries(ctx context.Context, cluster string, namespace st

 // GetPkgRepositories returns the list of package repositories for the given cluster and namespace
 func (s *Server) GetPkgRepositories(ctx context.Context, cluster, namespace string) ([]*apprepov1alpha1.AppRepository, error) {
-       resource, err := s.getPkgRepositoryResource(ctx, cluster, namespace)
+       resource, err := s.getPkgRepositoryResource(ctx, "default", "kubeapps")
```

```go
// GetPkgRepositories returns the list of package repositories for the given cluster and namespace
func (s *Server) GetPkgRepositories(ctx context.Context, cluster, namespace string) ([]*apprepov1alpha1.AppRepository, error) {
	//resource, err := s.getPkgRepositoryResource(ctx, cluster, namespace)
	resource, err := s.getPkgRepositoryResource(ctx, "default", "kubeapps")
	if err != nil {
		log.Infof("+[ERROR] helm GetPkgRepositories [%v]", err)
		return nil, err
	}
	log.InfoS("+[MATT] s.getPkgRepositoryResource", "resource", resource, "ctx", ctx, "cluster", "default", "namespace", "kubeapps")

	unstructured, err := resource.List(ctx, metav1.ListOptions{})
	log.InfoS("+[MATT] GetPkgRepositories unstructured", "unstructured", unstructured, "err", err)
```
Do you know why the frontend would be sending a gRPC request with that context `cluster="" namespace=""`?

Upon hardcoding I can view the catalog as expected, but cannot actually deploy a chart:

![image](https://user-images.githubusercontent.com/2043821/219471327-666523b4-95e0-4a44-9df7-c832ee0142b1.png)
![image](https://user-images.githubusercontent.com/2043821/219471347-ae23a1b2-1740-416a-b158-81b718659244.png)

**Comment by ppbaena** [comment]
@absoludity could you take a look at this issue to properly triage it? Thanks!

**Comment by absoludity** [comment]
> We have 2 `AppRepository` configured in this cluster (BTW what is the difference to the "PackageRepository" concept?):

It's just terminology: we were adding support for other types of repositories (Carvel, Flux) and needed common terminology in the code, so followed the precedent that was used in other VMware packaging projects.

I haven't been able to reproduce this yet, but do have one question: in your clusters config, why are you setting the `apiServiceURL`, assuming that this is the cluster on which Kubeapps is installed itself (so it should, by default, be using the default cluster internal address and cert which are on the pod, which is what happens if you don't specify it).

I'll keep trying to repro...

**Comment by mecampbellsoup** [comment]
> > We have 2 `AppRepository` configured in this cluster (BTW what is the difference to the "PackageRepository" concept?):
> 
> It's just terminology: we were adding support for other types of repositories (Carvel, Flux) and needed common terminology in the code, so followed the precedent that was used in other VMware packaging projects.

Gotcha, thanks for clarifying that.

> I haven't been able to reproduce this yet, but do have one question: in your clusters config, why are you setting the `apiServiceURL`, assuming that this is the cluster on which Kubeapps is installed itself (so it should, by default, be using the default cluster internal address and cert which are on the pod, which is what happens if you don't specify it).

We do this kind of hybrid approach (where we are as you point out really using the default cluster, but point to a different hostname via `apiServiceURL`) because we want to use our API gateway to authenticate/authorize all kubeapps requests to the k8s apiserver. So, in our kubeapps helm chart, we've added an `Ingress` (and a `Service` and `Endpoint` but I'll spare those details) so that requests from the kubeapps dashboard to the kubeapps backend(s) pass through our gateway and have our auth proxy headers `X-Consumer-Username` and `X-Consumer-Permissions` set.

> I'll keep trying to repro...

Thanks @absoludity appreciate the efforts very much 🙏 

Let me know if I can share anything else!

**Comment by absoludity** [comment]
> We do this kind of hybrid approach (where we are as you point out really using the default cluster, but point to a different hostname via `apiServiceURL`) because we want to use our API gateway to authenticate/authorize all kubeapps requests to the k8s apiserver.

Right, thanks for the explanation. So yes, I expect this is what's causing the difference in behavior. If you look at:

https://github.com/vmware-tanzu/kubeapps/blob/72f49c56048e5d670dd69d5daaeaf008a5e14d35/dashboard/src/components/Catalog/Catalog.tsx#L256-L264

the code is deciding there: if the current cluster is *not* the `kubeappsCluster`, it'll send the request *without* the namespace. Furthermore, if an empty namespace is passed to `fetchRepoSummaries`, it will send the `kubeappsCluster` as the cluster, which in your case (is currently determined to be unset by Kubeapps):

https://github.com/vmware-tanzu/kubeapps/blob/72f49c56048e5d670dd69d5daaeaf008a5e14d35/dashboard/src/actions/repos.ts#L88-L91

So why is Kubeapps unable to determine the cluster on which Kubeapps is installed here when there is only one cluster defined in your config? Because it's actually possible to install Kubeapps on one cluster (say, a management cluster) while configuring the clusters so that users can only install to a *different* target cluster... and that is what Kubeapps has determined here.

Which means the fix *should* be trivial: you should be able to simply add the `isKubeappsCluster` to explicitly let Kubeapps know that this cluster is the one on which Kubeapps is installed:

https://github.com/vmware-tanzu/kubeapps/blob/72f49c56048e5d670dd69d5daaeaf008a5e14d35/chart/kubeapps/values.yaml#L1398-L1400

Try setting that to true for your cluster and reload in your browser window and you *should* find that the request is sent with the correct context. Let me know if not.

**Comment by mecampbellsoup** [comment]
I just tried it quickly and it seems like due to setting `isKubeappsCluster: true` I can't get past the loading page...

![image](https://user-images.githubusercontent.com/2043821/220017843-20dd4db9-e9d1-4c93-9e29-8883ea87b537.png)

Specifically, now `CheckNamespaceExists` fails (and the page redirects in a loop):

```
[kubeappsapis] I0220 05:34:55.329917       1 namespaces.go:27] "+resources CheckNamespaceExists" cluster="default" namespace="default"
[kubeappsapis] I0220 05:34:55.331818       1 server.go:62] Unauthenticated 1.929287ms /kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists
[kubeappsapis] I0220 05:34:56.676626       1 namespaces.go:27] "+resources CheckNamespaceExists" cluster="default" namespace="default"
[kubeappsapis] I0220 05:34:56.678004       1 server.go:62] Unauthenticated 1.417298ms /kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists
[kubeappsapis] I0220 05:34:59.051849       1 namespaces.go:27] "+resources CheckNamespaceExists" cluster="default" namespace="default"
[kubeappsapis] I0220 05:34:59.054558       1 server.go:62] Unauthenticated 2.74887ms /kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists
[kubeappsapis] I0220 05:35:00.425865       1 namespaces.go:27] "+resources CheckNamespaceExists" cluster="default" namespace="default"
[kubeappsapis] I0220 05:35:00.428021       1 server.go:62] Unauthenticated 2.178464ms /kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists
[kubeappsapis] I0220 05:35:01.316712       1 namespaces.go:27] "+resources CheckNamespaceExists" cluster="default" namespace="default"
[kubeappsapis] I0220 05:35:01.318700       1 server.go:62] Unauthenticated 2.006769ms /kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists
```

```
  clusters:
    - name: default
      isKubeappsCluster: true
      apiServiceURL: https://cloud-app-kubernetes-ingress.cloud/k8s
      insecure: false
      certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvekNDQWVlZ0F3SUJBZ0lSQVA0VkppbWxoallaUnhkRjkyTC9MbVV3RFFZSktvWklodmNOQVFFTEJRQXcKR1RFWE1CVUdBMVVFQXhNT1kyOXlaWGRsWVhabExuUmxjM1F3SGhjTk1qTXdNakF5TVRVek1ERTRXaGNOTXpNdwpNakF5TURNek1ERTRXakFaTVJjd0ZRWURWUVFERXc1amIzSmxkMlZoZG1VdWRHVnpkRENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGl5U3lYN0V1dWI0ZytiTjFxUzUrT1RnclNhT0xaeEFwdGMKNWhkUXpYRWgvOFQ2YkNMMTdEb2lKVkExeGlZdXJFeDdHRnpFVWZFWWgvbDAyRjV4V01LMDRjUU9OQ1htRlNiNQpJMFhXTXpTWWpOaFpVdHZCOW5VMWlwZkUwSnI0Q2g4MEhwOUlmN2RLQXd1dHlMR2oxWGk0b2lHVmV0OFJ0akQyCjdBdERWS1JRa1BOSzVTSElyZjNxQzFwMEZTa1VwZUJ5bXJFSGNCZEF0ZTZnOXlsZDh3cU8zR2RGZjZWSW5BSHcKL0szcUtRK1VVUVY0dXRqWklKZ0JzTit4Sy9zanN0OUVlYloxWjZOTGx5YXIyT2p3bE1DdFVrUkhFZXFkRFp0bQo3cmw4ajZ0dmQzL1NQY0NRT2NQeWwwSDVxa0J4L3hUK0I3b0dpZmVrbm96QUxzay85V0VDQXdFQUFhTkNNRUF3CkRnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkIveE5LTHkKaVVOSThIaGtJN0doZ2c4alI5QzJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFoMFFOQ0ZuSVhVZ04vT2RXUApseGFScWk1cjU4VitxK245eTZZRHV3QmZYTUgreFFOdHphR3pTdm9TQ0paMTd2YVNheWxsTkdEV0hRUTJMU0tZClQ2ME1ZTE1aZnJHQVc5ZjVBampmek5ySURCdU4xKzZ1NzZ0T3BDcVBCeEEzMTB4LzhxRFEyeWJqL0p3N0w0WGwKSjR1OXlkeldXYjJZM3ZEOTVqTi9qNCt6dytIcUx5aGs2Mjg2MEJXOCtNakErMkNYVFJYdERUUGRRcTR2aGtrdQoyWlZ2L2pWUFFBeXQ0NW1XYkZQMVdqNlhEZlpvdzE5STRqTjM4ZkQ5L1I4TVFKMk1pZjNRb05oT2MzRlU1TnhnCmp6R0Q5dDN3US9kVHVCZy9jWHRPUEh1RlJZcGM3bXVlT1JkajMweWdrSTJwM0wwcm95LzZvekVzUkpzWU4vWW8KZnFlagotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
```
