### ISSUE TITLE
[Docs] error : Unable to load Kubeapps configuration:

### ISSUE THREAD

**Issue by AllardKrings** [vmware-tanzu/kubeapps#6273]
#### On Page: [/docs/latest/project/security/](https://kubeapps.dev/docs/latest/project/security/)

I cannot reach the dashboard. I get the error “Unable to load Kubeapps configuration:”

I am running a kubernetes cluster on 6 raspberry pi’s: three control plane nodes and three worker-nodes.

OS is Ubuntu 23.04

I followed the installation instructions EXACTLY.

any suggestions?

help appreciated!

**Comment by absoludity** [comment]
Hi there @AllardKrings . We'll need a bit more relevant information to be able to identify the problem that you're experiencing. Specifically, this error is displayed when your browser first starts loading the Kubeapps application: The web browser makes a request for `/config.json` and in your case that is failing. To help us understand why, can you please include a screenshot of the browser's javascript debugger's network tab, so we can see more information about the request to `/config.json` ? You should there see a request for the `/config.json` which you can then click on for more details about the issue that is causing the request to fail.

**Comment by mohbarryd** [comment]
Hello, 
I am getting the same error posted above after deploying kubeapps via the helm chart.
error:
`“Unable to load Kubeapps configuration:”`


here is my helm status:


```
helm status kubeapps
NAME: kubeapps
LAST DEPLOYED: Wed Jun  7 17:16:43 2023
NAMESPACE: kubeapps
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: kubeapps
CHART VERSION: 12.4.3
APP VERSION: 2.7.0** Please be patient while the chart is being deployed **

Tip:

  Watch the deployment status using the command: kubectl get pods -w --namespace kubeapps

Kubeapps can be accessed via port 80 on the following DNS name from within your cluster:

   kubeapps.kubeapps.svc.cluster.local

CAVEAT:
  Some App Repositories have been installed with a custom CA or authorization header.
  This generates secrets that won't be cleaned up if the repository is deleted through the Web application.
  You can delete them manually or when uninstalling this chart.

To access Kubeapps from outside your K8s cluster, follow the steps below:

1. Get the Kubeapps URL by running these commands:
   echo "Kubeapps URL: http://127.0.0.1:3000"
   kubectl port-forward --namespace kubeapps service/kubeapps 3000:80

2. Open a browser and access Kubeapps using the obtained URL.
```
 
 
 This is my /config.json
 
```
 {
  "kubeappsCluster": "default",
  "kubeappsNamespace": "kubeapps",
  "helmGlobalNamespace": "kubeapps",
  "carvelGlobalNamespace": "kapp-controller-packaging-global",
  "appVersion": "v2.7.0",
  "authProxyEnabled": true,
  "oauthLoginURI": "/apps/oauth2/start",
  "oauthLogoutURI": "/apps/oauth2/sign_out",
  "authProxySkipLoginPage": true,
  "featureFlags": {"apiOnly":{"enabled":false,"grpc":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"GRPC"}}},"operators":false,"schemaEditor":{"enabled":false}},
  "clusters": ["default"],
  "theme": "",
  "remoteComponentsUrl": "",
  "customAppViews": [],
  "skipAvailablePackageDetails": false,
  "createNamespaceLabels": {}
}
```
 help appreciated!
 Thanks!

**Comment by absoludity** [comment]
Hi @mohbarryd . Please see my [previous comment](https://github.com/vmware-tanzu/kubeapps/issues/6273#issuecomment-1576021628), which isn't requesting your `config.json` content (though that gives some info, thanks), but rather, opening the browser's network debug tab (part of the browser developer tools) and *finding* the request to `config.json`, clicking on that request to see the details, and taking a screenshot to put here. That will show us more information about *why* that request is failing. Thanks!

**Comment by mohbarryd** [comment]
Hi @absoludity thanks for the clarification.
I got pass that error by following your [ post ](https://github.com/vmware-tanzu/kubeapps/issues/3716#issuecomment-1067532124 )
I am using Istio Virtual service to route kubeapps to a path https://www.example.com/apps/.  Updating the rules with a reroute from /apis/ to / fixed that “Unable to load Kubeapps configuration:”
the updated Istio virtual service I am using:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  gateways:
  - gateway/www
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /apps/
    route:
    - destination:
        host: kubeapps.kubeapps.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /apis/
    rewrite:
      uri: /
    route:
    - destination:
        host: kubeapps-internal-kubeappsapis.kubeapps.svc.cluster.local
        port:
          number: 8080
```

But now I am facing a new error which is redirecting my /apps/ to /  with a 404 

here is the screenshot from the  browser's network debug:

![Screenshot_kubeapps-1](https://github.com/vmware-tanzu/kubeapps/assets/113537867/382c2d24-8d16-4d36-a647-9f648dec07dd)

These are my oidc paramaters, Looks like I am not using them correctly or missing some
```
  oauthLoginURI: /apps/oauth2/start
  oauthLogoutURI: /apps/oauth2/sign_out
  skipKubeappsLoginPage: true
  provider: "keycloak-oidc"
  clientID: "kubeapps"
  clientSecret: "REDACTED"
  cookieSecret: "REDACTED"
  existingOauth2Secret: ""
  cookieRefresh: 2m
  scope: "openid email groups"
  emailDomain: "*"
  extraFlags:
    - --oidc-issuer-url=https://auth.dcaic.example.com/auth/realms/DCAIC
    - --proxy-prefix=/apps/oauth2
    - --redirect-url=https://www.dcaic.example.com/apps/oauth2/callback
    - --skip-provider-button=true
```
Any idea ?

Thanks!
