### ISSUE TITLE
Helm release installation fails with fluxcd/helm-controller

### ISSUE THREAD

**Issue by project-administrator** [vmware-tanzu/kubeapps#6303]
**Describe the bug**

An attempt to install the helm release with *fluxcd/helm-controller* fails because of the following errors:
```
  Warning  error   97s (x8 over 3m21s)  helm-controller  Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 103: mapping key "initialDelaySeconds" already defined at line 97
  line 112: mapping key "initialDelaySeconds" already defined at line 106
```
Basically, helm chart generates an invalid template with duplicate keys in YAML. `fluxcd/helm-controller` would not tolerate this, but command-line `helm install` would silently remove the duplicate keys. 
Same issue from the `fluxcd/helm-controller` project: https://github.com/fluxcd/helm-controller/issues/283

**To Reproduce**

1. Install fluxcd with helm-controller running in the K8S cluster
2. Attempt to install the Install the kubeapps with `fluxcd/helm-controller` e.g.:
```
$ kubectl apply -f - <<EOF
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-repo-oci
  namespace: default
spec:
  interval: 6h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: default
spec:
  interval: 1h
  releaseName: kubeapps
  targetNamespace: default
  chart:
    spec:
      chart: kubeapps
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo-oci
        namespace: default
EOF
```
3. Check the failed deployment status: `kubectl describe helmrelease kubeapps`
**Expected behavior**
Helm chart should not generate multiple keys in the resulting YAML and deployment of the kubeapps helm chart should succeed with `fluxcd/helm-controller`.

- Helm chart version: 12.4.3
- Kubernetes version: 1.27.1

**Comment by absoludity** [comment]
Thanks @project-administrator . Confirmed that simply templating the chart results in the following for the kubeapps-apis service (which has initialDelaySeconds duplicated).

```yaml
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command: ["grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 10
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command: ["grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 5
```
