### ISSUE TITLE
Cannot configure securityContext of sync and cleanup jobs

### ISSUE THREAD

**Issue by RGPosadas** [vmware-tanzu/kubeapps#6545]
**Summary**
[`Sync`](https://github.com/vmware-tanzu/kubeapps/blob/23dac7b36f96d61a664cd32131dbf3c2f8800773/cmd/apprepository-controller/server/controller.go#L606) and [`cleanup`](https://github.com/vmware-tanzu/kubeapps/blob/23dac7b36f96d61a664cd32131dbf3c2f8800773/cmd/apprepository-controller/server/controller.go#L679) AppRepo jobs are currently not configureable to pass in container/pod SecurityContext. 

**Background and rationale**
We are in the middle of PSP to PSA migration. 
Currently, all core kubeapps components allow us to configure the container/pod SecurityContext - except for the Sync and Cleanup apprepository jobs.
Since we cannot configure the SecurityContext, the sync and cleanup jobs will be blocked from spawning pods if the namespace that kubeapps is running on has the `restricted` PodSecurity standard.

**Description/Acceptance Criteria**
Allow users to configure container/pod SecurityContext of the `sync` and `cleanup` jobs.

**Extra Info**
For apprepos that are defined as initialRepos, we are able to patch the `AppRepository` manifests, which allows us to define container/pod securityContext for the sync jobs. However, we do not have the same ability for the cleanup jobs.

**Comment by absoludity** [comment]
I just want to confirm that, when creating the AppRepository in Kubeapps, that you did specify the sync-job pod template? Asking because I can see in the code that we do intend to use that as the basis for the pod template used by the cron job that's created:

https://github.com/vmware-tanzu/kubeapps/blob/23dac7b36f96d61a664cd32131dbf3c2f8800773/cmd/apprepository-controller/server/controller.go#L627-L656

See https://kubeapps.dev/docs/latest/tutorials/managing-package-repositories/#modifying-the-synchronization-job for more info about customising the sync job pod template.

Can you please paste your `AppRepository` yaml to compare? (redacted if necessary)

Thanks

**Comment by RGPosadas** [comment]
Sample values definition:
```yaml
  apprepository:
    containerSecurityContext:
      runAsUser: 10001
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
```

Templated AppRepository:
```yaml
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  labels:
    app.kubernetes.io/instance: apps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeapps
    helm.sh/chart: kubeapps-12.4.6
  name: test-apprepo
  namespace: test-apprepo
spec:
  auth:
    header:
      secretKeyRef:
        key: authorizationHeader
        name: test-apprepo
  ociRepositories:
  - <redacted>
  syncJobPodTemplate:
    spec:
      securityContext:
        runAsUser: 10001
  type: oci
  url: <redacted>
````

Only the `securityContext.runAsUser` gets propagated down, as seen in https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/templates/apprepository/apprepositories.yaml#L42-L45
