### ISSUE TITLE
Self-made Helm chart secrets visibility

### ISSUE THREAD

**Issue by guillaume-ferry** [vmware-tanzu/kubeapps#6945]
**Summary**
Secrets of "self-made" Helm Charts does not appears in "Application Secrets" menu when chart is deployed.

**Description**
I've not found documentation on how to make secrets visible in "Application Secrets"

**Additional context**
Secret view is needed in a chart built with dependancy in mariadb

***Chart.yaml***
```
---
annotations:
  category: Web development
  licenses: Apache-2.0
apiVersion: v2
appVersion: "0.1.13"
name: mychart
dependencies:
- name: mariadb
  repository: https://charts.bitnami.com/bitnami
  tags:
    - mariadb
  version: 14.x.x
...
```

***secret.yaml***
```
apiVersion: v1
data:
  another-password: xxxxxxxx
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: l1
    meta.helm.sh/release-namespace: my-ns
    helm.sh/hook": pre-install
  labels:
    app.kubernetes.io/instance: l1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mychart
    app.kubernetes.io/version: 0.1.13
    helm.sh/chart: mychart-0.1.13
  name: l1-mychart
  namespace: my-ns
type: Opaque
```

However, secrets of mariadb chart are visible...

thank you in advance for your help,
regards,
Guillaume Ferry

**Comment by absoludity** [comment]
Hi @guillaume-ferry . There is no special treatment with secrets - other than they will only be visible in Kubeapps if they are created by the helm chart. If you look at the output yaml for mariadb, you'll see the chart creates a secret:

```
helm template bitnami/mariadb | grep "kind: Secret" -B2 -A12

# Source: mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.1.2
    helm.sh/chart: mariadb-14.0.1
type: Opaque
data:
  mariadb-root-password: "..."
```

Kubeapps is a UX for Helm (or other package managers), so if the secret is managed by Helm, then it should appear. If it is a secret referenced by your chart but that is not managed by your chart, it will not appear.

Let me know if that answers your question, or if there's a bug we need to look into. Thanks.
