### ISSUE TITLE
Feature Request: Templates for Creating Namespaces / Form in UI to Fill Template Variables

### ISSUE THREAD

**Issue by sspreitzer** [vmware-tanzu/kubeapps#6990]
**Summary**
Adding a feature to enable templates to create namespaces and filling template variables.

**Background and rationale**
Aside from deploying Helm charts and others, creating namespaces is not templated at the moment.

Allowing for namespace templates and UI forms would add namespace provisioning in which custom labels and annotations could be added to namespaces which could be further processed in policies, etc..

**Description**

- A configurable namespace template
- A ui form description to create a new namespace from that template

**Acceptance criteria**
Admins can define a namespace template and users can use that template to create a namespace.

Eg. configuration:
```yaml
namespace:
  template: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: {{ .name }}
      annotations:
        snakeoil.inc/multi-network-zone: {{ .network-zone }}
        snakeoil.inc/owner: {{ .email }}
  form:
    - name: name
      type: string
      description: Name of the Namespace
    - name: network-zone
      type: string
      default: default-zone
      description: Network Zone
    - name: email
      type: string
      description: Your Email
```

**Additional context**

Instead of having to select a namespace in the UI to create a Helm deployment, it could also be thought of to have the namespace be created as part of the Helm deployment. By specifying the Namespace name at the deployment, the Helm Chart including a values.schema.json and a Namespace definition
