### ISSUE TITLE
Kubeapps mis-handles a internal error when upgrading chart as an auth error and logs user out

### ISSUE THREAD

**Issue by Pivert** [vmware-tanzu/kubeapps#6991]
**Describe the bug**
When upgrading mariadb-galera, the KubeApps shows "The application is being deployed" for 1s, then back to the login page:
`There was an error connecting to the Kubernetes API. Please check that your token is valid.`

**To Reproduce**

1. Custom values files:
```
---
global:
  storageClass: "openebs-zfspv"
namespaceOverride: "galera"
service:
  type: LoadBalancer
  ports:
    mysql: 3306
  loadBalancerIP: "192.168.66.195"
persistence:
  size: 12Gi
metrics:
  enabled: true
  service:
    type: LoadBalancer
    port: 9104
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9104"
    loadBalancerIP: "192.168.66.195"
```
2. Install
```k create ns galera
kubens galera
helm install galera oci://registry-1.docker.io/bitnamicharts/mariadb-galera --values ./mariadb-galera-custom-values.yaml```
3. Galera is installed and Operator perfectly does the job.
4. Login to KubeApps with the kubeapps-operator-token, see that an upgrade is available, and Upgrade.
5. Your instantly logged off KubeApps: `There was an error connecting to the Kubernetes API. Please check that your token is valid.`
6. I did not find any relevant log in the pod logs.

**Expected behavior**
Proceed to the upgrade. (10.0.1 to 10.0.3)

**Desktop (please complete the following information):**
- All management commands from the pivert/seashell toolbox container running locally on WS
- Latest FireFox

- Version MariaDB Galera
App Version: 11.1.2
Package Version: 10.0.1
A new package version is available: 10.0.3. [Update Now](http://kubeapps.home.pivert.org/#/c/default/ns/galera/apps/helm.packages/v1alpha1/galera/upgrade/10.0.3)

- Kubernetes version v1.28.2+rke2r1 (No CIS profile)
- Package version 
  - Local helm for first installation: v3.12.3
  - KubeApps: v2.9.0

**Additional infos
I did try both with helm install (as described above), and with KubeApps install (preceding version 10.0.2).
In both cases, I'm logged off and back to login page when I want to upgrade. So it's not specific to manual helm install.
