### ISSUE TITLE
Postgresql Resource Settings are being ignored and stay default with HELM Chart Version 15.0.2

### ISSUE THREAD

**Issue by ILZ1105** [vmware-tanzu/kubeapps#7702]
**Describe the bug**
Postgresql Resource Settings are being ignored with HELM Chart Version 15.0.2

**To Reproduce**

1. Use either e resourcepreset or dial in your required resources in the part for postgres
2. Deploy the chart (done via kubeapps in my case)
3. Check the resources of the pod or the respctive statefulset
4. The values are still the defaults:
resources:
  limits:
    cpu: 150m
    ephemeral-storage: 1Gi
    memory: 192Mi
  requests:
    cpu: 100m
    ephemeral-storage: 50Mi
     memory: 128Mi

**Expected behavior**
It uses the respective resources as set manually or used via the resourcepresets.

**Screenshots**
None

**Desktop (please complete the following information):**

- Kubeapps Version 2.10.0
- Kubernetes version 1.26.5
- Package version Helm Chart version 15.0.2

**Additional context**
None

**Comment by antgamdia** [comment]
Mmm, interesting. I locally ran into some issues with postgresql recently, so perhaps this is the root cause. I'd rather report it in the `bitnami/charts` repository, as it is them who actually maintain the official chart.

**Comment by ILZ1105** [comment]
Good point, I listed the respective bug there: https://github.com/bitnami/charts/issues/25183

**Comment by eroldan** [comment]
I stepped into this problem today and did some investigation. The problem is that the subchart bitnami/postgres does not honor the postgresql.resources value. Probably because expanding the functionality, now the k8s resources need to be setup in postgres.primary.resources. For example a values.yaml:

```
postgresql:
  primary:
    resources:
      requests:
        cpu: 2000m
        memory: 512Mi
      limits:
        cpu: 3000m
        memory: 1024Mi

```

So, I consider the bug to be in the documentation ( https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/README.md?plain=1#L589 )

The upstream chart bitnami/postgres may have a bug indeed: not keeping previous compatibility if postgresql.resource was ever accepted as a value.

**Comment by velychkovsky** [comment]
I have the same issue, so I've successfully changed resources using values below:
```
postgresql:
  primary:
    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 512Mi
  persistence:
    enabled: true
```
