### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by SpeedGriffon** [vmware-tanzu/kubeapps#8263]
**Summary**
Syncing the `bitnami` repo exhausts the Docker pull rate limit leading to the `You have reached your unauthenticated pull rate limit. https://www.docker.com/increase-rate-limit` message.

The repo is enabled by default in `values.yaml`:
```yaml
  initialRepos:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
```

**Background and rationale**
This is caused by the combination of https://github.com/bitnami/charts/issues/30110 and https://github.com/bitnami/charts/issues/30853 and the fact that `kubeapps` tries to pull the whole repo during initialisation.

**Description**
I want to sync the `bitnami` repo without reaching the pull rate limit.
